name: React App CI/CD
on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      # Install Packages
      # - name: Install Packages
      #   run: npm install
      # Build the React app
      # - name: Build
      #   run: npm run build
      # # Run Tests
      # - name: Run Tests
      #   run: npm test